[package]
name = "liamt-raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = { version = "0.19", features = ["spirv"] }
nannou_egui = "0.19"
spirv-builder = { git = "https://github.com/rust-gpu/rust-gpu" }
shared = { path = "../shared" }
fps_ticker = "1.0.0"
glam = "0.29.2"
