[package]
name = "shaders"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
shared = { path = "../shared" }
spirv-std = { git = "https://github.com/rust-gpu/rust-gpu" }
